#!/usr/bin/env python3
"""Validate a project team generated by the construct-subagent skill.

The validator is read-only. It checks the project manifest, Codex custom-agent
TOML files, project agent settings, model assignments, skill paths, managed
file ownership, and the observed Codex runtime version. It requires Python 3.11
or newer, exits with 0 on success, and exits with 1 on validation failures.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import tomllib
from datetime import datetime
from pathlib import Path
from typing import Any


MANAGED_HEADER = "# Managed by construct-subagent. Edit via $construct-subagent."
VALID_CAPABILITY_TIERS = {"strong", "balanced", "throughput"}
VALID_COST_TIERS = {"high", "medium", "low"}
VALID_EFFORTS = {"minimal", "low", "medium", "high", "xhigh", "max", "ultra"}
VALID_SANDBOXES = {"read-only", "workspace-write", "danger-full-access"}
VALID_AVAILABILITY_SOURCES = {
    "runtime_model_registry",
    "codex_model_selector",
    "successful_model_probe",
}
VALID_CODEX_VERSION_SOURCES = {"codex_cli", "host_runtime"}
MINIMUM_CODEX_VERSION = (0, 145, 0)
MAXIMUM_REVIEWED_CODEX_SERIES = (0, 147)
NAME_PATTERN = re.compile(r"^[a-z][a-z0-9_]{0,63}$")
RFC3339_PATTERN = re.compile(
    r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$"
)
CODEX_VERSION_PATTERN = re.compile(
    r"^(?:codex(?:-cli)?\s+)?v?"
    r"(?P<major>0|[1-9]\d*)\."
    r"(?P<minor>0|[1-9]\d*)\."
    r"(?P<patch>0|[1-9]\d*)"
    r"(?:-(?P<prerelease>[0-9A-Za-z.-]+))?"
    r"(?:\+(?P<build>[0-9A-Za-z.-]+))?$",
    re.IGNORECASE,
)
CAPABILITY_RANK = {"throughput": 0, "balanced": 1, "strong": 2}
EFFORT_RANK = {
    "minimal": 0,
    "low": 1,
    "medium": 2,
    "high": 3,
    "xhigh": 4,
    "max": 5,
    "ultra": 6,
}


def parse_codex_version(raw_version: str) -> dict[str, Any] | None:
    """Parse the exact output of ``codex --version`` or a host runtime value."""
    match = CODEX_VERSION_PATTERN.fullmatch(raw_version.strip())
    if match is None:
        return None
    core = tuple(int(match.group(part)) for part in ("major", "minor", "patch"))
    prerelease = match.group("prerelease")
    build = match.group("build")
    normalized = ".".join(str(part) for part in core)
    if prerelease:
        normalized += f"-{prerelease}"
    if build:
        normalized += f"+{build}"
    return {
        "core": core,
        "series": core[:2],
        "prerelease": prerelease,
        "build": build,
        "normalized": normalized,
        "release_channel": "prerelease" if prerelease else "stable",
    }


class TeamValidator:
    """Collect validation errors without mutating the target project."""

    def __init__(
        self,
        root: Path,
        *,
        available_models: set[str] | None = None,
        availability_source: str | None = None,
        runtime_sandbox: str | None = None,
        runtime_approval_policy: str | None = None,
        require_runtime_permissions: bool = False,
        codex_version: str | None = None,
        codex_version_source: str | None = None,
    ) -> None:
        self.root = root.resolve()
        self.errors: list[str] = []
        self.availability_errors: list[str] = []
        self.runtime_permission_errors: list[str] = []
        self.codex_compatibility_errors: list[str] = []
        self.checked_files: set[Path] = set()
        self.available_models = available_models
        self.availability_source = availability_source
        self.runtime_sandbox = runtime_sandbox
        self.runtime_approval_policy = runtime_approval_policy
        self.require_runtime_permissions = require_runtime_permissions
        self.codex_version = codex_version
        self.codex_version_source = codex_version_source
        self.required_models: set[str] = set()
        self.manifest_availability_sources: set[str] = set()
        self.configured_agent_permissions: list[dict[str, Any]] = []

    def error(self, message: str) -> None:
        """Record a user-actionable validation error."""
        self.errors.append(message)

    def availability_error(self, message: str) -> None:
        """Record a failure in externally supplied runtime model evidence."""
        self.availability_errors.append(message)

    def runtime_permission_error(self, message: str) -> None:
        """Record a failure in externally supplied runtime permission evidence."""
        self.runtime_permission_errors.append(message)

    def codex_compatibility_error(self, message: str) -> None:
        """Record a failure in observed Codex runtime compatibility evidence."""
        self.codex_compatibility_errors.append(message)

    def load_toml(self, path: Path, label: str) -> dict[str, Any] | None:
        """Load a TOML file and report parse or type errors."""
        self.checked_files.add(path)
        try:
            with path.open("rb") as handle:
                data = tomllib.load(handle)
        except FileNotFoundError:
            self.error(f"{label} is missing: {path}")
            return None
        except (OSError, tomllib.TOMLDecodeError) as exc:
            self.error(f"{label} is not valid TOML: {path}: {exc}")
            return None
        if not isinstance(data, dict):
            self.error(f"{label} must contain a TOML table: {path}")
            return None
        return data

    def require_string(self, table: dict[str, Any], key: str, context: str) -> str | None:
        """Return a required non-empty string or record an error."""
        value = table.get(key)
        if not isinstance(value, str) or not value.strip():
            self.error(f"{context}.{key} must be a non-empty string")
            return None
        return value

    def require_string_list(
        self,
        table: dict[str, Any],
        key: str,
        context: str,
        *,
        allow_empty: bool = False,
    ) -> list[str] | None:
        """Return a required list of non-empty strings or record an error."""
        value = table.get(key)
        if not isinstance(value, list) or any(
            not isinstance(item, str) or not item.strip() for item in value
        ):
            self.error(f"{context}.{key} must be a list of non-empty strings")
            return None
        if not value and not allow_empty:
            self.error(f"{context}.{key} must not be empty")
        return value

    def validate_rfc3339_timestamp(
        self,
        table: dict[str, Any],
        key: str,
        context: str,
    ) -> None:
        """Require an RFC 3339 timestamp with an explicit UTC offset."""
        value = self.require_string(table, key, context)
        if value is None:
            return
        if not RFC3339_PATTERN.fullmatch(value):
            self.error(f"{context}.{key} must be a valid RFC 3339 timestamp")
            return
        try:
            parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        except ValueError:
            self.error(f"{context}.{key} must be a valid RFC 3339 timestamp")
            return
        if parsed.utcoffset() is None:
            self.error(f"{context}.{key} must include a UTC offset")

    def resolve_project_path(self, raw_path: str, context: str) -> Path | None:
        """Resolve a project-relative path and prevent traversal outside root."""
        candidate = Path(raw_path)
        if candidate.is_absolute():
            self.error(f"{context} must be project-relative, got: {raw_path}")
            return None
        resolved = (self.root / candidate).resolve()
        try:
            resolved.relative_to(self.root)
        except ValueError:
            self.error(f"{context} escapes the project root: {raw_path}")
            return None
        return resolved

    def validate_project(self, manifest: dict[str, Any]) -> None:
        """Validate the Project Execution Profile."""
        project = manifest.get("project")
        if not isinstance(project, dict):
            self.error("manifest.project must be a TOML table")
            return
        size = self.require_string(project, "size", "manifest.project")
        if size and size not in {"small", "medium", "large", "very-large"}:
            self.error("manifest.project.size must be small, medium, large, or very-large")
        self.require_string(project, "summary", "manifest.project")
        for key in ("complexity", "task_types", "risks", "priorities", "artifact_paths", "constraints"):
            values = self.require_string_list(project, key, "manifest.project")
            if key == "artifact_paths" and values:
                for index, raw_path in enumerate(values):
                    path = self.resolve_project_path(raw_path, f"manifest.project.artifact_paths[{index}]")
                    if path is not None and not path.exists():
                        self.error(f"project artifact does not exist: {raw_path}")
                    elif path is not None and not path.is_file():
                        self.error(f"project artifact must be a file: {raw_path}")

    def validate_orchestration(self, manifest: dict[str, Any]) -> int | None:
        """Validate centralized coordination and return the concurrency cap."""
        orchestration = manifest.get("orchestration")
        if not isinstance(orchestration, dict):
            self.error("manifest.orchestration must be a TOML table")
            return None
        coordinator = self.require_string(orchestration, "coordinator", "manifest.orchestration")
        if coordinator and coordinator != "main":
            self.error("manifest.orchestration.coordinator must be 'main'")
        topology = self.require_string(orchestration, "topology", "manifest.orchestration")
        if topology and topology != "flat":
            self.error("manifest.orchestration.topology must be 'flat'")
        if orchestration.get("agent_direct_dispatch") is not False:
            self.error("manifest.orchestration.agent_direct_dispatch must be false")
        concurrency = orchestration.get("max_concurrent_agents")
        if not isinstance(concurrency, int) or isinstance(concurrency, bool) or concurrency < 1:
            self.error("manifest.orchestration.max_concurrent_agents must be a positive integer")
            concurrency = None
        for key in ("parallel_policy", "serial_policy", "failure_flow"):
            self.require_string_list(orchestration, key, "manifest.orchestration")
        return concurrency

    def validate_models(self, manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
        """Validate the dynamic model registry and return it by model id."""
        registry = manifest.get("model_registry")
        models = registry.get("models") if isinstance(registry, dict) else None
        if not isinstance(models, list) or not models:
            self.error("manifest.model_registry.models must contain at least one model")
            return {}
        result: dict[str, dict[str, Any]] = {}
        model_order: list[str] = []
        for index, model in enumerate(models):
            context = f"manifest.model_registry.models[{index}]"
            if not isinstance(model, dict):
                self.error(f"{context} must be a TOML table")
                continue
            model_id = self.require_string(model, "id", context)
            availability_source = self.require_string(model, "availability_source", context)
            capability = self.require_string(model, "capability_tier", context)
            cost = self.require_string(model, "cost_tier", context)
            efforts = self.require_string_list(model, "reasoning_efforts", context)
            self.require_string_list(model, "suitable_for", context)
            if capability and capability not in VALID_CAPABILITY_TIERS:
                self.error(f"{context}.capability_tier is invalid: {capability}")
            if cost and cost not in VALID_COST_TIERS:
                self.error(f"{context}.cost_tier is invalid: {cost}")
            if efforts:
                unknown = sorted(set(efforts) - VALID_EFFORTS)
                if unknown:
                    self.error(f"{context}.reasoning_efforts contains invalid values: {unknown}")
            if availability_source:
                if availability_source not in VALID_AVAILABILITY_SOURCES:
                    self.error(
                        f"{context}.availability_source must be one of "
                        f"{sorted(VALID_AVAILABILITY_SOURCES)}, got: {availability_source}"
                    )
                else:
                    self.manifest_availability_sources.add(availability_source)
            if model_id:
                model_order.append(model_id)
                self.required_models.add(model_id)
                if model_id in result:
                    self.error(f"duplicate model id: {model_id}")
                else:
                    result[model_id] = model
        if model_order != sorted(model_order):
            self.error("manifest.model_registry.models must be sorted by id")
        return result

    def validate_runtime_model_availability(self) -> dict[str, Any]:
        """Compare required models with evidence supplied by the current runtime."""
        available = self.available_models
        source = self.availability_source
        missing = sorted(self.required_models - available) if available is not None else []
        status = "VERIFIED"

        if available is None or source is None:
            status = "UNVERIFIED"
            self.availability_error(
                "runtime model availability evidence was not supplied; pass "
                "--availability-source and at least one --available-model from the "
                "current Codex runtime or model selector"
            )
        elif source not in VALID_AVAILABILITY_SOURCES:
            status = "FAIL"
            self.availability_error(
                f"runtime availability source must be one of "
                f"{sorted(VALID_AVAILABILITY_SOURCES)}, got: {source}"
            )
        elif not available:
            status = "FAIL"
            self.availability_error("runtime availability evidence contains no models")
        else:
            if self.manifest_availability_sources != {source}:
                status = "FAIL"
                self.availability_error(
                    "Manifest availability_source values do not match the external "
                    f"runtime evidence source {source}: "
                    f"{sorted(self.manifest_availability_sources)}"
                )
            if missing:
                status = "FAIL"
                self.availability_error(
                    f"models required by the Manifest are absent from current runtime "
                    f"evidence: {missing}"
                )

        return {
            "status": status,
            "source": source,
            "required_models": sorted(self.required_models),
            "available_models": sorted(available) if available is not None else [],
            "missing_models": missing,
            "errors": list(self.availability_errors),
        }

    def validate_runtime_permissions(self) -> dict[str, Any]:
        """Compare configured sandbox defaults with the observed parent runtime.

        Codex reapplies the parent's live sandbox and approval overrides when a
        subagent is spawned. The custom Agent file therefore expresses a
        configured default, not an unconditional effective permission grant.
        """
        sandbox = self.runtime_sandbox
        approval_policy = self.runtime_approval_policy
        evidence_supplied = sandbox is not None and approval_policy is not None
        status = "VERIFIED"

        if not evidence_supplied:
            status = "UNVERIFIED"
            if self.require_runtime_permissions:
                self.runtime_permission_error(
                    "parent runtime permission evidence was not supplied; pass "
                    "--runtime-sandbox and --runtime-approval-policy from the "
                    "current parent session"
                )
        elif sandbox not in VALID_SANDBOXES:
            status = "MISMATCH"
            self.runtime_permission_error(
                f"parent runtime sandbox must be one of {sorted(VALID_SANDBOXES)}, "
                f"got: {sandbox}"
            )
        elif not approval_policy.strip():
            status = "UNVERIFIED"
            if self.require_runtime_permissions:
                self.runtime_permission_error(
                    "parent runtime approval policy must be a non-empty observed value"
                )

        agents: list[dict[str, Any]] = []
        for configured in self.configured_agent_permissions:
            configured_sandbox = configured["configured_sandbox_default"]
            comparison_status = "UNVERIFIED"
            if sandbox in VALID_SANDBOXES:
                comparison_status = "MATCH" if sandbox == configured_sandbox else "MISMATCH"
                if comparison_status == "MISMATCH":
                    status = "MISMATCH"
                    self.runtime_permission_error(
                        f"Agent {configured['name']} configured sandbox default "
                        f"{configured_sandbox} does not match observed parent runtime "
                        f"sandbox {sandbox}; the parent live override may determine the "
                        "spawned Agent's effective sandbox"
                    )
            agents.append({**configured, "comparison_status": comparison_status})

        return {
            "status": status,
            "required": self.require_runtime_permissions,
            "observed_parent": {
                "sandbox_mode": sandbox,
                "approval_policy": approval_policy,
            },
            "agents": agents,
            "behavioral_boundary_enforcement": "developer_instructions_only",
            "errors": list(self.runtime_permission_errors),
        }

    def validate_runtime_codex_compatibility(self) -> dict[str, Any]:
        """Classify the observed Codex version against the reviewed schema window."""
        raw_version = self.codex_version
        source = self.codex_version_source
        parsed = parse_codex_version(raw_version) if raw_version is not None else None
        status = "VERIFIED"

        if raw_version is None or source is None:
            status = "UNVERIFIED"
            self.codex_compatibility_error(
                "Codex runtime version evidence was not supplied; pass --codex-version "
                "and --codex-version-source using the current local client or host runtime"
            )
        elif source not in VALID_CODEX_VERSION_SOURCES:
            status = "UNVERIFIED"
            self.codex_compatibility_error(
                f"Codex version source must be one of "
                f"{sorted(VALID_CODEX_VERSION_SOURCES)}, got: {source}"
            )
        elif parsed is None:
            status = "UNVERIFIED"
            self.codex_compatibility_error(
                f"Codex runtime version is not parseable: {raw_version!r}; expected "
                "a value such as 'codex-cli 0.147.0'"
            )
        else:
            core = parsed["core"]
            prerelease = parsed["prerelease"]
            if core < MINIMUM_CODEX_VERSION or (
                core == MINIMUM_CODEX_VERSION and prerelease is not None
            ):
                status = "UNSUPPORTED_OLD"
                self.codex_compatibility_error(
                    f"Codex {parsed['normalized']} predates the minimum stable compatible "
                    f"version {'.'.join(str(part) for part in MINIMUM_CODEX_VERSION)}"
                )
            elif parsed["series"] > MAXIMUM_REVIEWED_CODEX_SERIES:
                status = "UNREVIEWED_NEWER"
                self.codex_compatibility_error(
                    f"Codex series {parsed['series'][0]}.{parsed['series'][1]} is newer than "
                    f"the maximum reviewed series "
                    f"{MAXIMUM_REVIEWED_CODEX_SERIES[0]}."
                    f"{MAXIMUM_REVIEWED_CODEX_SERIES[1]}; update construct-subagent's "
                    "contract, validator, and tests before generating target Agent files"
                )

        return {
            "status": status,
            "source": source,
            "observed": raw_version,
            "normalized_version": parsed["normalized"] if parsed is not None else None,
            "release_channel": parsed["release_channel"] if parsed is not None else None,
            "minimum_version": ".".join(str(part) for part in MINIMUM_CODEX_VERSION),
            "maximum_reviewed_series": (
                f"{MAXIMUM_REVIEWED_CODEX_SERIES[0]}."
                f"{MAXIMUM_REVIEWED_CODEX_SERIES[1]}.x"
            ),
            "errors": list(self.codex_compatibility_errors),
        }

    def validate_skill_path(self, raw_path: str, context: str) -> None:
        """Validate a project-relative, home-relative, or absolute Skill path."""
        expanded = Path(raw_path).expanduser()
        path = expanded if expanded.is_absolute() else self.root / expanded
        skill_file = path if path.name == "SKILL.md" else path / "SKILL.md"
        if not skill_file.is_file():
            self.error(f"{context} does not resolve to a Skill: {raw_path}")

    def validate_agent_file(
        self,
        agent: dict[str, Any],
        context: str,
        path: Path,
        skills: list[str],
    ) -> None:
        """Validate a Codex custom-agent file against its manifest entry."""
        self.checked_files.add(path)
        try:
            content = path.read_text(encoding="utf-8")
        except OSError as exc:
            self.error(f"{context}.file cannot be read: {path}: {exc}")
            return
        first_line = content.splitlines()[0] if content.splitlines() else ""
        if first_line != MANAGED_HEADER:
            self.error(f"{context}.file is not owned by construct-subagent: {path}")
            return
        try:
            config = tomllib.loads(content)
        except tomllib.TOMLDecodeError as exc:
            self.error(f"{context}.file is not valid TOML: {path}: {exc}")
            return
        for key in ("name", "description", "model", "model_reasoning_effort", "sandbox_mode"):
            if config.get(key) != agent.get(key):
                self.error(f"{context}.file {key} does not match the manifest")
        instructions = config.get("developer_instructions")
        if not isinstance(instructions, str) or not instructions.strip():
            self.error(f"{context}.file developer_instructions must be non-empty")
        configured_skills: list[str] = []
        skill_table = config.get("skills")
        if isinstance(skill_table, dict):
            entries = skill_table.get("config", [])
            if not isinstance(entries, list):
                self.error(f"{context}.file skills.config must be an array of tables")
            else:
                for skill_index, entry in enumerate(entries):
                    if not isinstance(entry, dict):
                        self.error(f"{context}.file skills.config[{skill_index}] must be a table")
                        continue
                    path_value = entry.get("path")
                    if not isinstance(path_value, str) or not path_value.strip():
                        self.error(f"{context}.file skills.config[{skill_index}].path must be non-empty")
                        continue
                    if entry.get("enabled") is not True:
                        self.error(f"{context}.file skills.config[{skill_index}].enabled must be true")
                    configured_skills.append(path_value)
        elif skill_table is not None:
            self.error(f"{context}.file skills must be a TOML table")
        if configured_skills != skills:
            self.error(f"{context}.file Skill bindings do not match the manifest")

    def validate_agents(
        self,
        manifest: dict[str, Any],
        models: dict[str, dict[str, Any]],
    ) -> None:
        """Validate all active agents and detect managed orphan definitions."""
        agents = manifest.get("agents")
        if not isinstance(agents, list) or not agents:
            self.error("manifest.agents must contain at least one Subagent")
            return
        names: set[str] = set()
        active_paths: set[Path] = set()
        agent_order: list[str] = []
        for index, agent in enumerate(agents):
            context = f"manifest.agents[{index}]"
            if not isinstance(agent, dict):
                self.error(f"{context} must be a TOML table")
                continue
            name = self.require_string(agent, "name", context)
            raw_file = self.require_string(agent, "file", context)
            self.require_string(agent, "description", context)
            required_lists: dict[str, list[str] | None] = {}
            for key in (
                "responsibilities",
                "boundaries",
                "escalation_triggers",
                "permission_boundaries",
                "inputs",
                "outputs",
                "invoke_when",
                "parallel_groups",
            ):
                required_lists[key] = self.require_string_list(agent, key, context)
            for key in ("skills", "tools", "serializes_with"):
                self.require_string_list(agent, key, context, allow_empty=True)
            if name:
                agent_order.append(name)
                if not NAME_PATTERN.fullmatch(name):
                    self.error(f"{context}.name must match {NAME_PATTERN.pattern}: {name}")
                if name in names:
                    self.error(f"duplicate agent name: {name}")
                names.add(name)
            if agent.get("managed") is not True:
                self.error(f"{context}.managed must be true")
            sandbox = self.require_string(agent, "sandbox_mode", context)
            if sandbox and sandbox not in VALID_SANDBOXES:
                self.error(f"{context}.sandbox_mode is invalid: {sandbox}")
            if sandbox:
                self.configured_agent_permissions.append(
                    {
                        "name": name or context,
                        "configured_sandbox_default": sandbox,
                        "permission_boundaries": required_lists.get("permission_boundaries") or [],
                        "behavioral_boundaries": required_lists.get("boundaries") or [],
                    }
                )
            cost_tier = self.require_string(agent, "cost_tier", context)
            if cost_tier and cost_tier not in VALID_COST_TIERS:
                self.error(f"{context}.cost_tier is invalid: {cost_tier}")
            model_id = self.require_string(agent, "model", context)
            effort = self.require_string(agent, "model_reasoning_effort", context)
            escalation_model = self.require_string(agent, "escalation_model", context)
            escalation_effort = self.require_string(agent, "escalation_reasoning_effort", context)
            self.validate_model_assignment(model_id, effort, cost_tier, models, context, "default")
            self.validate_model_assignment(
                escalation_model,
                escalation_effort,
                None,
                models,
                context,
                "escalation",
            )
            self.validate_escalation_strength(
                model_id,
                effort,
                escalation_model,
                escalation_effort,
                models,
                context,
            )
            skills = agent.get("skills") if isinstance(agent.get("skills"), list) else []
            for skill_index, skill_path in enumerate(skills):
                if isinstance(skill_path, str):
                    self.validate_skill_path(skill_path, f"{context}.skills[{skill_index}]")
            if raw_file:
                path = self.resolve_project_path(raw_file, f"{context}.file")
                if path is not None:
                    expected_parent = (self.root / ".codex" / "agents").resolve()
                    if path.parent != expected_parent or path.suffix != ".toml":
                        self.error(f"{context}.file must be an active .codex/agents/*.toml file")
                    else:
                        if path in active_paths:
                            self.error(
                                f"{context}.file is referenced by multiple manifest Agents: "
                                f"{raw_file}"
                            )
                        active_paths.add(path)
                        self.validate_agent_file(agent, context, path, skills)
        if agent_order != sorted(agent_order):
            self.error("manifest.agents must be sorted by name")
        agents_dir = self.root / ".codex" / "agents"
        if agents_dir.is_dir():
            for path in agents_dir.glob("*.toml"):
                try:
                    first_line = path.read_text(encoding="utf-8").splitlines()[0]
                except (OSError, IndexError):
                    continue
                if first_line == MANAGED_HEADER and path.resolve() not in active_paths:
                    self.error(f"managed active Agent is missing from the manifest: {path}")

    def validate_model_assignment(
        self,
        model_id: str | None,
        effort: str | None,
        cost_tier: str | None,
        models: dict[str, dict[str, Any]],
        context: str,
        assignment: str,
    ) -> None:
        """Check that an Agent assignment is supported by the model registry."""
        if not model_id or model_id not in models:
            if model_id:
                self.error(f"{context}.{assignment} model is absent from the registry: {model_id}")
            return
        model = models[model_id]
        efforts = model.get("reasoning_efforts", [])
        if effort and effort not in efforts:
            self.error(f"{context}.{assignment} effort {effort} is not supported by {model_id}")
        if cost_tier and cost_tier != model.get("cost_tier"):
            self.error(f"{context}.cost_tier does not match registry model {model_id}")

    def validate_escalation_strength(
        self,
        default_model_id: str | None,
        default_effort: str | None,
        escalation_model_id: str | None,
        escalation_effort: str | None,
        models: dict[str, dict[str, Any]],
        context: str,
    ) -> None:
        """Require the escalation assignment to be stronger than the default."""
        if (
            not default_model_id
            or default_model_id not in models
            or not escalation_model_id
            or escalation_model_id not in models
            or default_effort not in EFFORT_RANK
            or escalation_effort not in EFFORT_RANK
        ):
            return
        default_capability = models[default_model_id].get("capability_tier")
        escalation_capability = models[escalation_model_id].get("capability_tier")
        if (
            default_capability not in CAPABILITY_RANK
            or escalation_capability not in CAPABILITY_RANK
        ):
            return
        default_strength = (
            CAPABILITY_RANK[default_capability],
            EFFORT_RANK[default_effort],
        )
        escalation_strength = (
            CAPABILITY_RANK[escalation_capability],
            EFFORT_RANK[escalation_effort],
        )
        if escalation_strength <= default_strength:
            self.error(
                f"{context}.escalation assignment must be strictly stronger than "
                "the default assignment by capability tier, then reasoning effort"
            )

    def validate_project_config(self, concurrency: int | None) -> None:
        """Validate project-wide Codex multi-agent settings."""
        config_path = self.root / ".codex" / "config.toml"
        config = self.load_toml(config_path, "project Codex config")
        if config is None:
            return
        agents = config.get("agents")
        if not isinstance(agents, dict):
            self.error(".codex/config.toml must contain an [agents] table")
            return
        if agents.get("enabled") is not True:
            self.error(".codex/config.toml [agents].enabled must be true")
        cap = agents.get("max_concurrent_threads_per_session")
        if not isinstance(cap, int) or isinstance(cap, bool) or cap < 1:
            self.error(
                ".codex/config.toml [agents].max_concurrent_threads_per_session "
                "must be a positive integer"
            )
        elif concurrency is not None and cap != concurrency:
            self.error("project config concurrency does not match the manifest")

    def validate(self) -> dict[str, Any]:
        """Run all checks and return a JSON-serializable report."""
        manifest_path = self.root / ".codex" / "agent-team.toml"
        manifest = self.load_toml(manifest_path, "Agent Team Manifest")
        if manifest is not None:
            if manifest.get("schema_version") != 1:
                self.error("manifest.schema_version must be 1")
            if manifest.get("generator") != "construct-subagent":
                self.error("manifest.generator must be 'construct-subagent'")
            if manifest.get("status") != "ready":
                self.error("manifest.status must be 'ready'")
            self.validate_rfc3339_timestamp(manifest, "last_changed_at", "manifest")
            self.validate_project(manifest)
            concurrency = self.validate_orchestration(manifest)
            models = self.validate_models(manifest)
            self.validate_agents(manifest, models)
            self.validate_project_config(concurrency)
        availability = self.validate_runtime_model_availability()
        runtime_permissions = self.validate_runtime_permissions()
        runtime_codex_compatibility = self.validate_runtime_codex_compatibility()
        fingerprint = self.fingerprint()
        all_errors = [
            *self.errors,
            *self.availability_errors,
            *self.runtime_permission_errors,
            *self.codex_compatibility_errors,
        ]
        return {
            "status": "PASS" if not all_errors else "FAIL",
            "configuration_status": "PASS" if not self.errors else "FAIL",
            "runtime_model_availability": availability,
            "runtime_permissions": runtime_permissions,
            "runtime_codex_compatibility": runtime_codex_compatibility,
            "root": str(self.root),
            "checked_files": len(self.checked_files),
            "fingerprint": fingerprint,
            "errors": all_errors,
        }

    def fingerprint(self) -> str:
        """Hash checked managed inputs to support external idempotency comparisons."""
        digest = hashlib.sha256()
        for path in sorted(self.checked_files):
            if not path.is_file():
                continue
            try:
                relative = path.resolve().relative_to(self.root)
            except ValueError:
                relative = path.resolve()
            digest.update(str(relative).encode("utf-8"))
            digest.update(b"\0")
            digest.update(path.read_bytes())
            digest.update(b"\0")
        return digest.hexdigest()


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True, help="Target Codex project root")
    parser.add_argument(
        "--availability-source",
        choices=sorted(VALID_AVAILABILITY_SOURCES),
        help="Independent source that exposed the current runtime's available models",
    )
    parser.add_argument(
        "--available-model",
        action="append",
        dest="available_models",
        help="Model id exposed by that source; repeat once per available model",
    )
    parser.add_argument(
        "--runtime-sandbox",
        choices=sorted(VALID_SANDBOXES),
        help="Sandbox mode observed on the current parent session",
    )
    parser.add_argument(
        "--runtime-approval-policy",
        help="Approval policy observed on the current parent session",
    )
    parser.add_argument(
        "--require-runtime-permissions",
        action="store_true",
        help="Fail unless parent runtime permission evidence is supplied and matches",
    )
    parser.add_argument(
        "--codex-version",
        help="Exact output of codex --version or the equivalent current host runtime value",
    )
    parser.add_argument(
        "--codex-version-source",
        choices=sorted(VALID_CODEX_VERSION_SOURCES),
        help="Independent source that exposed the current Codex runtime version",
    )
    parser.add_argument("--json", action="store_true", help="Emit the validation report as JSON")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Run validation and print a concise result with remediation details."""
    args = parse_args(argv if argv is not None else sys.argv[1:])
    available_models = set(args.available_models) if args.available_models is not None else None
    validator = TeamValidator(
        args.root,
        available_models=available_models,
        availability_source=args.availability_source,
        runtime_sandbox=args.runtime_sandbox,
        runtime_approval_policy=args.runtime_approval_policy,
        require_runtime_permissions=args.require_runtime_permissions,
        codex_version=args.codex_version,
        codex_version_source=args.codex_version_source,
    )
    report = validator.validate()
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print(
            f"{report['status']}: construct-subagent team at {report['root']} "
            f"({report['checked_files']} files, fingerprint {report['fingerprint']})"
        )
        print(
            f"Configuration: {report['configuration_status']}; runtime model availability: "
            f"{report['runtime_model_availability']['status']}; runtime permissions: "
            f"{report['runtime_permissions']['status']}; Codex compatibility: "
            f"{report['runtime_codex_compatibility']['status']}"
        )
        for error in validator.errors:
            print(f"ERROR: {error}")
        for error in validator.availability_errors:
            print(f"AVAILABILITY_ERROR: {error}")
        for error in validator.runtime_permission_errors:
            print(f"RUNTIME_PERMISSION_ERROR: {error}")
        for error in validator.codex_compatibility_errors:
            print(f"CODEX_COMPATIBILITY_ERROR: {error}")
    if report["status"] == "PASS":
        print("Validation complete. No files were changed.", file=sys.stderr)
        return 0
    print("Validation failed. Fix the reported team contract violations.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
